### ISSUE TITLE
support: trait bound and choose impl place

### ISSUE THREAD

**Issue by huang12zheng** [xfix/extension-trait#11]
* test case:
```rs
#[extension_trait]
pub impl IUncontrolledProviderScope for u32 {
    type ProviderContainer: PartialEq = u32;
}
#[extension_trait]
impl StructPattern for i32 {
    #[intrait]
    fn x(X { a, b }: X) -> i32 {
        a + b
    }
}
```
A Messy implementation ：https://github.com/huang12zheng/extension-trait

**Comment by sugar700** [comment]
This create is no longer maintained, consider using [extend](https://lib.rs/crates/extend) or [easy-ext](https://lib.rs/crates/easy-ext) instead.
